/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as BrandsRouteImport } from './routes/brands'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SpecialRouteImport } from './routes/special'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as ArticlesIndexRouteImport } from './routes/articles/index'
import { Route as BrandsIndexRouteImport } from './routes/brands/index'
import { Route as CartIndexRouteImport } from './routes/cart/index'
import { Route as CategoriesIndexRouteImport } from './routes/categories/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as SearchIndexRouteImport } from './routes/search/index'
import { Route as SpecialIndexRouteImport } from './routes/special/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsRoute = BrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialRoute = SpecialRouteImport.update({
  id: '/special',
  path: '/special',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArticlesRoute,
} as any)
const BrandsIndexRoute = BrandsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BrandsRoute,
} as any)
const CartIndexRoute = CartIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CartRoute,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CategoriesRoute,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsRoute,
} as any)
const SearchIndexRoute = SearchIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SearchRoute,
} as any)
const SpecialIndexRoute = SpecialIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SpecialRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/articles': typeof ArticlesRouteWithChildren
  '/brands': typeof BrandsRouteWithChildren
  '/cart': typeof CartRouteWithChildren
  '/categories': typeof CategoriesRouteWithChildren
  '/products': typeof ProductsRouteWithChildren
  '/search': typeof SearchRouteWithChildren
  '/special': typeof SpecialRouteWithChildren
  '/account/': typeof AccountIndexRoute
  '/articles/': typeof ArticlesIndexRoute
  '/brands/': typeof BrandsIndexRoute
  '/cart/': typeof CartIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/search/': typeof SearchIndexRoute
  '/special/': typeof SpecialIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountIndexRoute
  '/articles': typeof ArticlesIndexRoute
  '/brands': typeof BrandsIndexRoute
  '/cart': typeof CartIndexRoute
  '/categories': typeof CategoriesIndexRoute
  '/products': typeof ProductsIndexRoute
  '/search': typeof SearchIndexRoute
  '/special': typeof SpecialIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/articles': typeof ArticlesRouteWithChildren
  '/brands': typeof BrandsRouteWithChildren
  '/cart': typeof CartRouteWithChildren
  '/categories': typeof CategoriesRouteWithChildren
  '/products': typeof ProductsRouteWithChildren
  '/search': typeof SearchRouteWithChildren
  '/special': typeof SpecialRouteWithChildren
  '/account/': typeof AccountIndexRoute
  '/articles/': typeof ArticlesIndexRoute
  '/brands/': typeof BrandsIndexRoute
  '/cart/': typeof CartIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/search/': typeof SearchIndexRoute
  '/special/': typeof SpecialIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/articles'
    | '/brands'
    | '/cart'
    | '/categories'
    | '/products'
    | '/search'
    | '/special'
    | '/account/'
    | '/articles/'
    | '/brands/'
    | '/cart/'
    | '/categories/'
    | '/products/'
    | '/search/'
    | '/special/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/articles'
    | '/brands'
    | '/cart'
    | '/categories'
    | '/products'
    | '/search'
    | '/special'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/articles'
    | '/brands'
    | '/cart'
    | '/categories'
    | '/products'
    | '/search'
    | '/special'
    | '/account/'
    | '/articles/'
    | '/brands/'
    | '/cart/'
    | '/categories/'
    | '/products/'
    | '/search/'
    | '/special/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRouteWithChildren
  ArticlesRoute: typeof ArticlesRouteWithChildren
  BrandsRoute: typeof BrandsRouteWithChildren
  CartRoute: typeof CartRouteWithChildren
  CategoriesRoute: typeof CategoriesRouteWithChildren
  ProductsRoute: typeof ProductsRouteWithChildren
  SearchRoute: typeof SearchRouteWithChildren
  SpecialRoute: typeof SpecialRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands': {
      id: '/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof BrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/special': {
      id: '/special'
      path: '/special'
      fullPath: '/special'
      preLoaderRoute: typeof SpecialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/articles/': {
      id: '/articles/'
      path: '/'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/brands/': {
      id: '/brands/'
      path: '/'
      fullPath: '/brands/'
      preLoaderRoute: typeof BrandsIndexRouteImport
      parentRoute: typeof BrandsRoute
    }
    '/cart/': {
      id: '/cart/'
      path: '/'
      fullPath: '/cart/'
      preLoaderRoute: typeof CartIndexRouteImport
      parentRoute: typeof CartRoute
    }
    '/categories/': {
      id: '/categories/'
      path: '/'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof CategoriesRoute
    }
    '/products/': {
      id: '/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/search/': {
      id: '/search/'
      path: '/'
      fullPath: '/search/'
      preLoaderRoute: typeof SearchIndexRouteImport
      parentRoute: typeof SearchRoute
    }
    '/special/': {
      id: '/special/'
      path: '/'
      fullPath: '/special/'
      preLoaderRoute: typeof SpecialIndexRouteImport
      parentRoute: typeof SpecialRoute
    }
  }
}

interface AccountRouteChildren {
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface ArticlesRouteChildren {
  ArticlesIndexRoute: typeof ArticlesIndexRoute
}

const ArticlesRouteChildren: ArticlesRouteChildren = {
  ArticlesIndexRoute: ArticlesIndexRoute,
}

const ArticlesRouteWithChildren = ArticlesRoute._addFileChildren(
  ArticlesRouteChildren,
)

interface BrandsRouteChildren {
  BrandsIndexRoute: typeof BrandsIndexRoute
}

const BrandsRouteChildren: BrandsRouteChildren = {
  BrandsIndexRoute: BrandsIndexRoute,
}

const BrandsRouteWithChildren =
  BrandsRoute._addFileChildren(BrandsRouteChildren)

interface CartRouteChildren {
  CartIndexRoute: typeof CartIndexRoute
}

const CartRouteChildren: CartRouteChildren = {
  CartIndexRoute: CartIndexRoute,
}

const CartRouteWithChildren = CartRoute._addFileChildren(CartRouteChildren)

interface CategoriesRouteChildren {
  CategoriesIndexRoute: typeof CategoriesIndexRoute
}

const CategoriesRouteChildren: CategoriesRouteChildren = {
  CategoriesIndexRoute: CategoriesIndexRoute,
}

const CategoriesRouteWithChildren = CategoriesRoute._addFileChildren(
  CategoriesRouteChildren,
)

interface ProductsRouteChildren {
  ProductsIndexRoute: typeof ProductsIndexRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsIndexRoute: ProductsIndexRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

interface SearchRouteChildren {
  SearchIndexRoute: typeof SearchIndexRoute
}

const SearchRouteChildren: SearchRouteChildren = {
  SearchIndexRoute: SearchIndexRoute,
}

const SearchRouteWithChildren =
  SearchRoute._addFileChildren(SearchRouteChildren)

interface SpecialRouteChildren {
  SpecialIndexRoute: typeof SpecialIndexRoute
}

const SpecialRouteChildren: SpecialRouteChildren = {
  SpecialIndexRoute: SpecialIndexRoute,
}

const SpecialRouteWithChildren =
  SpecialRoute._addFileChildren(SpecialRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRouteWithChildren,
  ArticlesRoute: ArticlesRouteWithChildren,
  BrandsRoute: BrandsRouteWithChildren,
  CartRoute: CartRouteWithChildren,
  CategoriesRoute: CategoriesRouteWithChildren,
  ProductsRoute: ProductsRouteWithChildren,
  SearchRoute: SearchRouteWithChildren,
  SpecialRoute: SpecialRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
